from typing import Protocol


class EntityRepository(Protocol):
    async def save(self, entity_id: str, data: dict) -> None: ...
    async def load(self, entity_id: str) -> dict | None: ...
    async def list_living(self) -> list[str]: ...
    async def archive(self, entity_id: str) -> None: ...
    async def load_archive(self, entity_id: str) -> dict | None: ...
